twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
        '%kernel.project_dir%/vendor/lexik/form-filter-bundle/Resources/views': LexikFormFilterBundle
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@LexikFormFilterBundle/Form/form_div_layout.html.twig'
    globals:
        helper: '@App\Factory\HelperFactory'

